lang: node_js
node_js:
    - 8
    - 9
cache:
    yarn: true
    directories:
        - node_modules
        - packages/create-react-app/node_modules
        - packages/react-scripts/node_modules

install: true
script:
    - yarn install
    - yarn test

before_deploy:
    - yarn build

deploy:
    skip_cleanup: true
    provider: surge
    project: ./build
    domain: omed.surge.sh